services:
  - type: web
    name: url-shortener
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: url-db
          property: connectionString

databases:
  - name: url-db
